// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfigurationHandler(arg1) {
  return window['go']['main']['App']['AddConfigurationHandler'](arg1);
}

export function AddTranslationHandler(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTranslationHandler'](arg1, arg2, arg3);
}

export function DowloadConfigHandler() {
  return window['go']['main']['App']['DowloadConfigHandler']();
}
