// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfiguration(arg1) {
  return window['go']['main']['App']['AddConfiguration'](arg1);
}

export function DivideTabs(arg1, arg2, arg3) {
  return window['go']['main']['App']['DivideTabs'](arg1, arg2, arg3);
}

export function DowloadConfig() {
  return window['go']['main']['App']['DowloadConfig']();
}
